# Generated by Django 5.0.2 on 2024-03-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_filmwork_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(
                choices=[
                    ('ACTOR', 'Actor'),
                    ('DIRECTOR', 'Director'),
                    ('WRITER', 'Writer')
                ],
                verbose_name='role'
            ),
        ),
    ]
